version: '3.8'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:80
    volumes:
      - drupal_data:/bitnami/drupal
    depends_on:
        - mariadb
  db:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - USER = YAM428
      - PASSWORD = 030720110
      - DATABASE = final
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drupal